name: Rust

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup rust environment
        run: |
          cd contracts
          rustup update stable
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          cargo install cargo-tarpaulin
          cargo install cargo-dylint dylint-link
          cargo install cargo-contract --force --locked

      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd contracts
          cargo +nightly contract build --verbose --release
      
      - name: Test
        run: |
          cd contracts
          SUMMARY="$(RUST_BACKTRACE=1 cargo +nightly test --no-default-features --features std --verbose -- --nocapture | tail -7 | head -1)"
          if [[ ${SUMMARY:0:16} == "test result: ok." ]]; then exit 0; else exit 1; fi
