name: Rust

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ls
        run: |
          pwd
          echo ls -la
          ls -la
          echo ls -la ~
          ls -la ~

      - name: Restore cached cargo-env
        id: restore-cache-cargo-env
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo
            ~/.dylint_drivers
          key: ${{ runner.os }}-cargo-env-v2-

      - name: Setup rust environment
        if: steps.restore-cache-cargo-env.outputs.cache-hit != 'true'
        run: |
          echo install nightly
          rustup toolchain install nightly-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          # to compile the std lib we nee the src
          rustup default nightly-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          echo set browser wasm target
          rustup target add wasm32-unknown-unknown --toolchain nightly
          # echo install tarpaulin and dylint
          # cargo +nightly install cargo-tarpaulin cargo-dylint dylint-link
          echo install cargo-contract
          cargo install cargo-contract --version 2.0.0-rc

      - name: Update rust
        id: update-rust
        run: |
          if [[ $(rustup update | wc -l) -gt 2 ]]; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Update cargo
        id: update-cargo
        run: |
          if [[ $(rustup update | wc -l) -gt 4 ]]; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Save cargo-env to cache
        if: steps.restore-cache-cargo-env.outputs.cache-hit != 'true' || steps.update-cargo.outputs.upgraded == 'true' || steps.update-rust.outputs.upgraded == 'true'
        id: save-cache-cargo-env
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo
            ~/.dylint_drivers
          key: ${{ runner.os }}-cargo-env-$(date +%s)

      - name: Restore cached cargo build
        id: restore-cache-cargo-build
        uses: actions/cache/restore@v3
        with:
          path: |
            ./contracts/target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-v2

      - name: Configure rust environment
        run: |
          # to compile the std lib we nee the src
          rustup default nightly-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build
        run: |
          cd contracts
          cargo contract build --optimization-passes 0
      
      - name: Save cargo build to cache
        id: save-cache-cargo-build-1
        uses: actions/cache/save@v3
        with:
          path: |
            ./contracts/target
          key: ${{ steps.restore-cache-cargo-build.outputs.cache-primary-key }}

      - name: Test
        run: |
          cd contracts
          RUST_BACKTRACE=1 cargo test --no-default-features --features std -- --nocapture
          exit $?

      - name: Save cargo build to cache
        id: save-cache-cargo-build-2
        uses: actions/cache/save@v3
        with:
          path: |
            ./contracts/target
          key: ${{ steps.restore-cache-cargo-build.outputs.cache-primary-key }}
