name: Rust

on:
  push:
    branches: [ main, workflow ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          cd contracts
          rustup update stable
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          cargo install cargo-tarpaulin
      - name: Run the unit tests
        run: |
          cd contracts
          SUMMARY="$(cargo +nightly test --no-default-features --features std --verbose -- --nocapture | tail -7 | head -1)"
          if [[ ${SUMMARY:0:16} == "test result: ok." ]]; then exit 0; else exit 1; fi
