name: Rust

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Restore cached cargo
        id: cache-cargo-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo
      
      - name: Setup rust environment
        run: |
          cd contracts
          rustup update stable
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          cargo install cargo-tarpaulin
          cargo install cargo-dylint dylint-link
          cargo install cargo-contract --force --locked

      - name: Save cargo cache
        id: cache-cargo-save
        uses: actions/cache/save@v3
        with:
          path: ~/.cargo
          key: ${{ steps.cache-cargo-restore.outputs.cache-primary-key }}

      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd contracts
          cargo +nightly contract build --verbose --release
      
      - name: Test
        run: |
          cd contracts
          SUMMARY="$(RUST_BACKTRACE=1 cargo +nightly test --no-default-features --features std --verbose -- --nocapture | tail -7 | head -1)"
          if [[ ${SUMMARY:0:16} == "test result: ok." ]]; then exit 0; else exit 1; fi
