name: Rust

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cached cargo-env
        id: restore-cache-cargo-env
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo
            ~/.dylint_drivers
          key: ${{ runner.os }}-cargo-env

      - name: Setup rust environment
        if: steps.restore-cache-cargo-env.outputs.cache-hit != 'true'
        run: |
          echo install nightly
          rustup update nightly
          echo set browser wasm target
          rustup target add wasm32-unknown-unknown --toolchain nightly
          echo install tarpaulin and dylint
          cargo +nightly install cargo-tarpaulin cargo-dylint dylint-link
          echo install cargo-contract
          cargo +nightly install cargo-contract --version 2.0.0-rc

      - name: Tmp
        run: |
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Save cargo-env to cache
        id: save-cache-cargo-env
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo
            ~/.dylint_drivers
          key: ${{ steps.restore-cache-cargo-env.outputs.cache-primary-key }}

      - name: Build
        run: |
          cd contracts
          cargo +nightly contract build --verbose --release
      
      - name: Test
        run: |
          cd contracts
          exec 5>&1
          SUMMARY="$(RUST_BACKTRACE=1 cargo +nightly test --no-default-features --features std --verbose -- --nocapture | tee >(cat - >&5))"
          SUMMARY=$(echo $SUMMARY | tail -7 | head -1)
          if [[ ${SUMMARY:0:16} == "test result: ok." ]]; then exit 0; else exit 1; fi

