name: Rust

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

env:
  CARGO_TERM_COLOR: always
  cargo_env_version: cargo-env
  cargo_build_version: cargo-build
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ls
        run: |
          pwd
          echo ls -la
          ls -la
          echo ls -la ~
          ls -la ~

      ################ SETUP RUST

      - name: Restore cached cargo-env
        id: restore-cache-cargo-env
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo
            ~/.dylint_drivers
          key: ${{ runner.os }}-${{ env.cargo_env_version }}

      - name: Setup rust environment
        if: steps.restore-cache-cargo-env.outputs.cache-hit != 'true'
        run: |
          echo install nightly
          rustup toolchain install nightly-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          # to compile the std lib we nee the src
          rustup default nightly-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          echo set browser wasm target
          rustup target add wasm32-unknown-unknown --toolchain nightly
          # echo install tarpaulin and dylint
          # cargo +nightly install cargo-tarpaulin cargo-dylint dylint-link
          echo install cargo-contract
          cargo install cargo-contract --version 2.0.0-rc

      - name: Update rust
        run: |
          rustup update

      - name: Update cargo
        run: |
          cd contracts
          cargo update

      - name: Clear cargo env cache
        continue-on-error: true
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches?key=${{ runner.os }}-${{ env.cargo_env_version }}

      - name: Save cargo env to cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo
            ~/.dylint_drivers
          key: ${{ runner.os }}-${{ env.cargo_env_version }}

      ################ BUILD

      - name: Restore cached cargo build
        id: restore-cache-cargo-build
        uses: actions/cache/restore@v3
        with:
          path: |
            ./contracts/target
          key: ${{ runner.os }}-${{ env.cargo_build_version }}

      - name: Build
        run: |
          cd contracts
          cargo contract build --optimization-passes 0

      - name: Clear cargo build cache
        continue-on-error: true
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches?key=${{ runner.os }}-${{ env.cargo_build_version }}

      - name: Save cargo build to cache
        uses: actions/cache/save@v3
        with:
          path: |
            ./contracts/target
          key: ${{ runner.os }}-${{ env.cargo_build_version }}

      ################ TEST

      - name: Test
        run: |
          cd contracts
          RUST_BACKTRACE=1 cargo test --no-default-features --features std -- --nocapture
          exit $?

      - name: Clear cargo build cache
        continue-on-error: true
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches?key=${{ runner.os }}-${{ env.cargo_build_version }}

      - name: Save cargo build to cache
        uses: actions/cache/save@v3
        with:
          path: |
            ./contracts/target
          key: ${{ runner.os }}-${{ env.cargo_build_version }}